title: Yezun
description: Persönliche Website von Tim
baseurl: ""
url: "https://yezun.de"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
